--- #YAML:1.0
name: File-Read
version: 0.04
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: Unique interface for reading one or more files
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
